-- Your SQL goes here
CREATE TYPE group_status AS ENUM ('open', 'closed');
CREATE TABLE groups (
  id int generated by default as identity primary key,
  name varchar check(length(name) >= 2 and length(name) <= 23) NOT NULL UNIQUE,
  current_state group_status DEFAULT 'open' NOT NULL
);